apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: orheqw6j2-python
  janus-idp.io/tekton: orheqw6j2-python
  backstage.io/kubernetes-id: orheqw6j2-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: orheqw6j2-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
